version: '3'
services:
  web:
    build: ./DjanGoDocker
    command: python ./manage.py runserver 0.0.0.0:8000
    ports:
    - 8000:8000
    volumes:
    - ./DjanGoDocker:/code
    depends_on:
    - db

  db:
    image: 'postgres:12-alpine'
    restart : always
    environment:
     DATABASE_URL: postgres://postgres@db/postgres
     POSTGRES_PASSWORD: postgres